# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(),
        ),
    ]
